baseurl = "https://colmaris.fr"
title = "colmaris"
theme = "hugo-theme-console"
languageCode = 'fr-FR'
defaultContentLanguage = "fr"
defaultContentLang = "fr"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 

  [[params.navlinks]]
  name = "infos/"
  url = "about/"

  [[params.navlinks]]
  name = "blog/"
  url = "posts/"
  
  [[params.navlinks]]
  name = "photographie/"
  url = "photos/"
